name: Build Mac Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install universal binary compatible numpy if possible
        pip install pandas rich scipy pyinstaller
        
    - name: Build Mac executable (single arch)
      run: |
        cd packaging/mac
        # Remove target_arch='universal2' from spec
        pyinstaller text_ranking_tool_mac.spec
        
    - name: Upload Mac executable
      uses: actions/upload-artifact@v4
      with:
        name: TextRankingTool-Mac-v1.0
        path: packaging/mac/dist/TextRankingTool
